theme: jekyll-theme-minimal
title: CONGRATULATIONS ON SOLVING MY PUZZLE!
description: Do you want to try my text based adventure game? Click this url to play it or this url to customize it for yourself!
